### PR TITLE
 Added support to java, python and C#.

### PR DESCRIPTION
**Pull request by endes0**
Also, was created interface for mutex (For the different implementations in the different platforms).

### CODE REVIEW

**Comment by thomasuster** [comment]
Hey this looks great!

Would you do the following?

- [ ] Rebase on latest master
- [ ] Fix CI for C# dependency
- [ ] Remove any whitespace only changes showing in diffs

**Comment by thomasuster** [comment]
@endes123321 Hey there! Got the trunk passing CI. Would you rebase it on master and resolve conflicts?

```
git fetch
git rebase upstream/master
//resolve any conflicts
git push --force
```

Thank you

**Comment by endes0** [comment]
Sorry, i don't know very well how to rebase, but I think this time I did well.

**Comment by thomasuster** [comment]
Hey, I'm having trouble getting this compiling locally. Any ideas?

screen shot 2017-09-22 at 9 46 45 pm

**Comment by endes0** [comment]
What is your haxe version?? Can you give me the full build log??.
In haxe 3.4.2 compiles well.

**Comment by thomasuster** [comment]
@endes123321 Ahh! Thank you, I was on 4.0.0. I installed haxe 3.4.3 and it all the targets built. There's still a couple of issues, would you do the following?

1) This branch is just one commit behind master, would you rebase after a fetch?
```
git remote add upstream git@github.com:thomasuster/haxe-threadpool.git
git fetch upstream
git rebase upstream/master
```

2) Would you add the three new targets to CI?(.appveyor and travis)? The java, c#, and python TestMain 10 should all run on CI.

**Comment by endes0** [comment]
Only to travis CI, because I dont know how to install java and python in Appveyor

**Comment by thomasuster** [comment]
It looks like you didn't do the rebase yet. Please do that first, it should just be a FF(Fast Forward for me). This might work for .appveyor for csharp.
```
cinst jre8 -y
```
@andyli do you happen to know cinst for csharp?

**Comment by andyli** [comment]
> do you happen to know cinst for csharp?

There is already C# (.Net framework) pre-installed:
https://www.appveyor.com/docs/build-environment/#net-framework

**Comment by endes0** [comment]
Sorry, I forgot to do a git rebase.I just added the new platforms to .appveyor (I think it should work).

**Comment by endes123321** [comment]
By the way, sorry for my lack of experience with git rebase and Appveyor.

**Comment by thomasuster** [comment]
Fantastic, looks like you just need one final change in .travis since it appears python is already installed.

So just change 
```
brew install neko haxe python mono
```
to
```
brew install neko haxe mono
```
And I bet you'll be good.

**Comment by thomasuster** [comment]
Thanks for the PR @endes123321 !!! Do you have twitter?

**Comment by endes0** [comment]
yes, but I barely use it. https://twitter.com/endes3000

**Pull request merged**
